name: tests

trigger: ["*"]
pr: ["*"]

pool:
  vmImage: "ubuntu-latest"

variables:
  # Try to checkout the matching branch, if the command fails, don't care.
  BRANCH_NAME: $[coalesce(variables['System.PullRequest.SourceBranch'], variables['System.PullRequest.TargetBranch'], replace(variables['Build.SourceBranch'], 'refs/heads/', ''))]

resources:
  containers:
    - container: redis
      image: redis
      ports:
        - 6379:6379
    - container: elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
      env:
        xpack.security.enabled: true
        discovery.type: single-node
        ES_JAVA_OPTS: "-Xms256m -Xmx512m"
        ELASTIC_PASSWORD: devpass
      ports:
        - 9200:9200
    - container: minio
      image: cccs/minio
      env:
        MINIO_ROOT_USER: al_storage_key
        MINIO_ROOT_PASSWORD: Ch@ngeTh!sPa33w0rd
      ports:
        - 9000:9000
    - container: openldap
      image: docker.io/bitnami/openldap:2.6
      env:
        LDAP_PORT_NUMBER: 389
        LDAP_ROOT: dc=assemblyline,dc=local
        LDAP_ADMIN_PASSWORD: admin
        LDAP_USERS: ldap_user
        LDAP_PASSWORDS: ldap_password
        LDAP_USER_OU: people
      ports:
        - 389:389

  repositories:
    - repository: assemblyline-base
      type: github
      endpoint: github-repo-sa
      name: CybercentreCanada/assemblyline-base
    - repository: assemblyline-core
      type: github
      endpoint: github-repo-sa
      name: CybercentreCanada/assemblyline-core

jobs:
  - job: run_test
    strategy:
      matrix:
        python3_9:
          python.version: "3.9"
        Python3_10:
          python.version: "3.10"
        Python3_11:
          python.version: "3.11"

    timeoutInMinutes: 15
    services:
      elasticsearch: elasticsearch
      redis: redis
      minio: minio

    steps:
      - task: UsePythonVersion@0
        displayName: Set python version
        inputs:
          versionSpec: "$(python.version)"
      - checkout: self
        displayName: Checkout assemblyline-ui
      - checkout: assemblyline-base
        displayName: Checkout assemblyline-base
      - checkout: assemblyline-core
        displayName: Checkout assemblyline-core
      - script: |
          sudo mkdir -p /etc/assemblyline/
          sudo mkdir -p /var/cache/assemblyline/
          sudo mkdir -p /var/lib/assemblyline/
          sudo cp pipelines/config.yml /etc/assemblyline
          sudo chmod a+rw /var/cache/assemblyline/
          sudo chmod a+rw /var/lib/assemblyline/
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev libfuzzy-dev python3-dev libldap2-dev libsasl2-dev wget
          sudo env "PATH=$PATH" "PIP_USE_PEP517=true" python -m pip install -U pip setuptools wheel
        displayName: Setup Environment
        workingDirectory: $(Pipeline.Workspace)/s/assemblyline-ui
      - script: |
          git checkout -b $BRANCH_NAME -t origin/$BRANCH_NAME || true
          sudo env "PATH=$PATH" "PIP_USE_PEP517=true" python -m pip install --no-cache-dir -e .
        displayName: Install assemblyline
        workingDirectory: $(Pipeline.Workspace)/s/assemblyline-base
      - script: |
          git checkout -b $BRANCH_NAME -t origin/$BRANCH_NAME || true
          sudo env "PATH=$PATH" "PIP_USE_PEP517=true" python -m pip install --no-cache-dir -e .
        displayName: Install assemblyline-core
        workingDirectory: $(Pipeline.Workspace)/s/assemblyline-core
      - script: |
          sudo env "PATH=$PATH" "PIP_USE_PEP517=true" python -m pip install --no-cache-dir -e .[test,socketio]
        displayName: Install assemblyline-ui
        workingDirectory: $(Pipeline.Workspace)/s/assemblyline-ui
      - script: |
          sudo cp test/config/classification.yml /etc/assemblyline
          python -m assemblyline_ui.app &
          wget https://localhost:5000/healthz/live --no-check-certificate --timeout=2 --waitretry=10 --retry-connrefused

          python -m assemblyline_ui.socketsrv &
          wget https://localhost:5002/healthz/live --no-check-certificate --timeout=2 --waitretry=10 --retry-connrefused

          sudo docker run -d --name frontend --network host --restart on-failure cccs/assemblyline-ui-frontend &
          sudo docker run -d --name nginx --network host --restart on-failure -e "FRONTEND_HOST=localhost" -e "UI_HOST=localhost" -e "SOCKET_HOST=localhost" -e "TEMPLATE=minimal" -e "FQDN=localhost" cccs/nginx-ssl-frontend
          wget https://localhost --no-check-certificate --timeout=2 --retry-on-http-error=502 --waitretry=10 --retry-connrefused

          pytest -rsx -vv
        workingDirectory: $(Pipeline.Workspace)/s/assemblyline-ui
        displayName: Test
