name: tests

trigger: ["*"]
pr: ["*"]

pool:
  vmImage: "ubuntu-latest"

variables:
  # Try to checkout the matching branch, if the command fails, don't care.
  BRANCH_NAME: $[coalesce(variables['System.PullRequest.SourceBranch'], variables['System.PullRequest.TargetBranch'], replace(variables['Build.SourceBranch'], 'refs/heads/', ''))]

resources:
  repositories:
    - repository: assemblyline-base
      type: github
      endpoint: github-repo-sa
      name: CybercentreCanada/assemblyline-base
    - repository: assemblyline-core
      type: github
      endpoint: github-repo-sa
      name: CybercentreCanada/assemblyline-core

jobs:
  - job: run_test
    strategy:
      matrix:
        Python3_10:
          python.version: "3.10"
        Python3_11:
          python.version: "3.11"

    timeoutInMinutes: 15
    steps:
      - task: UsePythonVersion@0
        displayName: Set python version
        inputs:
          versionSpec: "$(python.version)"
      - checkout: self
        displayName: Checkout assemblyline-ui
      - checkout: assemblyline-base
        displayName: Checkout assemblyline-base
      - checkout: assemblyline-core
        displayName: Checkout assemblyline-core
      - script: |
          sudo mkdir -p /etc/assemblyline/
          sudo mkdir -p /var/cache/assemblyline/
          sudo mkdir -p /var/lib/assemblyline/
          sudo chmod a+rw /var/cache/assemblyline/
          sudo chmod a+rw /var/lib/assemblyline/
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev libfuzzy-dev python3-dev libldap2-dev libsasl2-dev wget
          sudo env "PATH=$PATH" "PIP_USE_PEP517=true" python -m pip install -U pip setuptools wheel
        displayName: Setup Environment
        workingDirectory: $(Pipeline.Workspace)/s/assemblyline-ui
      - script: |
          git checkout -b $BRANCH_NAME -t origin/$BRANCH_NAME || true
          sudo env "PATH=$PATH" "PIP_USE_PEP517=true" python -m pip install --no-cache-dir -e .
        displayName: Install assemblyline
        workingDirectory: $(Pipeline.Workspace)/s/assemblyline-base
      - script: |
          git checkout -b $BRANCH_NAME -t origin/$BRANCH_NAME || true
          sudo env "PATH=$PATH" "PIP_USE_PEP517=true" python -m pip install --no-cache-dir -e .
        displayName: Install assemblyline-core
        workingDirectory: $(Pipeline.Workspace)/s/assemblyline-core
      - script: |
          sudo env "PATH=$PATH" "PIP_USE_PEP517=true" python -m pip install --no-cache-dir -e .[test,socketio]
        displayName: Install assemblyline-ui
        workingDirectory: $(Pipeline.Workspace)/s/assemblyline-ui
      - script: |
          # Start up dependencies
          sudo docker compose --progress=quiet -f test/docker-compose.yml up -d --wait

          # Install configuration & classification files
          sudo cp test/config/classification.yml /etc/assemblyline/classification.yml
          sudo cp test/config/config.yml /etc/assemblyline/config.yml

          # Start test
          pytest -rsx -vv
        workingDirectory: $(Pipeline.Workspace)/s/assemblyline-ui
        displayName: Test
