core:
  alerter:
    delay: 0
  metrics:
    apm_server:
      server_url: http://localhost:8200/
    elasticsearch:
      hosts: ["http://elastic:devpass@localhost:9200"]
    redis:
      host: localhost
  redis:
    nonpersistent:
      host: localhost
      port: 6379
    persistent:
      host: localhost
      port: 6379

datastore:
  hosts: ["http://elastic:devpass@localhost:9200"]

filestore:
  cache:
    [
      "s3://al_storage_key:Ch@ngeTh!sPa33w0rd@localhost:9000?s3_bucket=al-cache&use_ssl=False",
    ]
  storage:
    [
      "s3://al_storage_key:Ch@ngeTh!sPa33w0rd@localhost:9000?s3_bucket=al-storage&use_ssl=False",
    ]

submission:
  metadata:
    ingest:
      _default:
        test:
          validator_type: keyword
          required: true
      strict_ingest:
        test:
          validator_type: keyword
    strict_schemes:
      - strict_ingest
  profiles:
    # Profile that will enforce metadata validation
    - name: "static"
      display_name: "Static Analysis"
      params:
        type: strict_ingest
        services:
          excluded: ["Dynamic Analysis"]
      restricted_params:
        submission: ["ignore_recursion_prevention"]

logging:
  log_level: DISABLED
  log_to_console: false
  log_to_file: false
  log_to_syslog: false

ui:
  enforce_quota: false
