from copy import copy
from ipaddress import ip_address, ip_network

import elasticapm
import jwt
import requests
from assemblyline.odm.models.user import load_roles_form_acls

from assemblyline_ui.config import CACHE, LOGGER, STORAGE, config, get_token_store
from assemblyline_ui.helper.oauth import get_profile_identifiers
from assemblyline_ui.helper.user import get_request_ip
from assemblyline_ui.http_exceptions import AuthenticationException


@elasticapm.capture_span(span_type='authentication')
def get_jwks_keys(url):
    cache_key = CACHE.create_key("jwks", url)
    jwks = CACHE.get(cache_key, reset=False)

    # Go get it is not in cache
    if not jwks:
        jwks = requests.get(url).json()

        # Save it to the cache
        CACHE.set(cache_key, jwks, ttl=600)

    return jwks["keys"]


@elasticapm.capture_span(span_type='authentication')
def validate_oauth_id(username, oauth_token_id):
    # This function identifies the user via a saved oauth_token_id in redis
    if not config.auth.oauth.enabled and oauth_token_id:
        raise AuthenticationException("oAuth login is disabled")

    if config.auth.oauth.enabled and oauth_token_id:
        if get_token_store(username, 'oauth').exist(oauth_token_id):
            return username

        raise AuthenticationException("Invalid token")

    return None


@elasticapm.capture_span(span_type='authentication')
def validate_oauth_token(oauth_token, return_user=False) -> tuple[str|dict, list, str]:
    """ Validate an OAuth token and return the associated user and roles.

        Args:
            oauth_token (str): The OAuth token to validate.
            oauth_provider (str): The name of the OAuth provider.
            return_user (bool): Whether to return the full user object (dict) or just the username (str).

        Returns:
            tuple[str, list, str]: A tuple containing the username or user object, the roles, and the impersonator in an On-Behalf-Of flow.
    """

    headers = jwt.get_unverified_header(oauth_token)
    if 'token_id' in headers and 'user' in headers:
        # This isn't an OAuth token, but rather a token that was generated by Assemblyline to represent an OAuth token.
        raise AuthenticationException("Invalid token - Assemblyline generated token given, not an OAuth token.")

    # This function identifies the user via an externally provided oauth token
    if not config.auth.oauth.enabled and oauth_token:
        raise AuthenticationException("oAuth login is disabled")

    if config.auth.oauth.enabled and oauth_token:
        # Decode the token without verification to extract the issuer (iss) claim to see if we can map it to a configured oauth provider
        oauth_provider_config = None
        try:
            unverified_claims = jwt.decode(oauth_token, options={"verify_signature": False})
            issuer = unverified_claims['iss']
        except jwt.PyJWTError as e:
            raise AuthenticationException(f"Invalid token - {str(e)}")

        # With the issuer claim, find the corresponding oauth provider configuration that has a matching api_base_url
        for name, provider in config.auth.oauth.providers.items():
            if provider.api_base_url == issuer:
                oauth_provider_config = provider
                oauth_provider = name
                break

        if not oauth_provider_config:
            raise AuthenticationException(f"Invalid oAuth provider: {oauth_provider}")

        if not oauth_provider_config.allow_external_tokens:
            raise AuthenticationException(f"External tokens are not accepted for oAuth provider: {oauth_provider}")

        if not oauth_provider_config.jwks_uri:
            raise AuthenticationException(f"oAuth provider '{oauth_provider}' does not have a jwks_uri configured.")

        # Check if user is allowed to use this OAuth provider from its IP
        ip = ip_address(get_request_ip())
        if oauth_provider_config.ip_filter and not any(ip in ip_network(cidr) for cidr in oauth_provider_config.ip_filter):
            raise AuthenticationException(f"Access from IP {ip} is not allowed for oAuth provider: {oauth_provider}")

        # Gather provider valid audiences
        audiences = copy(oauth_provider_config.external_token_alternate_audiences)
        audiences.append(oauth_provider_config.client_id)

        # Find proper signing key
        key_list = get_jwks_keys(oauth_provider_config.jwks_uri)
        signing_key = None
        for key in key_list:
            if key['kid'] == headers['kid']:
                signing_key = jwt.api_jwk.PyJWK(key)
                break

        if signing_key:
            try:
                # Decode token using signing key and audiences
                jwt_data = jwt.decode(
                    oauth_token,
                    signing_key.key,
                    algorithms=[oauth_provider_config.jwt_token_alg],
                    audience=audiences)
            except jwt.PyJWTError as e:
                raise AuthenticationException(f"Invalid token - {str(e)}")

            profile_identifiers = get_profile_identifiers(jwt_data, oauth_provider_config)
            impersonator = None

            # Lookup user via its profile identifiers (email or identity_id)
            for k, v in profile_identifiers.items():
                if v is not None:
                    # Get user from it's email
                    users = STORAGE.user.search(f"{k}:{v}", fl="*", as_obj=False, rows=1)['items']
                    if users:
                        user = users[0]
                        # Limit user logging in from external token to only user READ/WRITE APIs
                        roles = load_roles_form_acls(["R", "W"], [])
                        if user['roles']:
                            # Limit the user's effective roles to only those that they have within R/W
                            roles = list(set(roles).intersection(set(user['roles'])))

                        # Check if the token has an authorized party (azp) claim that differs from the provider's client_id, this can indicate a delegation or impersonation scenario where the token was issued to a different client on behalf of the user.
                        if jwt_data.get("azp") and jwt_data["azp"] != oauth_provider_config.client_id:
                            impersonator = jwt_data["azp"]
                            LOGGER.info(f"Token was issued to a client [{impersonator}] on behalf of a user: {user['uname']}")

                            # Check the scopes claim to see if we need to limit the session's roles based on the scopes provided in the token.
                            if oauth_provider_config.scope_field not in jwt_data:
                                raise AuthenticationException(f"Token does not contain the expected '{oauth_provider_config.scope_field}' claim for oAuth provider '{oauth_provider}'.")
                            else:
                                # We want to explicitly check for the 'scope' field in the auto_properties configuration to limit roles based on the scope claim in the token.
                                jwt_scopes = jwt_data[oauth_provider_config.scope_field].split(" ")
                                scope_props = [prop for prop in oauth_provider_config.auto_properties
                                               if prop['field'] == oauth_provider_config.scope_field and prop['type'] == 'role']

                                if not scope_props:
                                    # No auto_properties configuration for 'scope' was found, so we will not limit the roles based on the scopes in the token.
                                    LOGGER.info(f"No auto_properties configuration for '{oauth_provider_config.scope_field }' found in oAuth provider '{oauth_provider}'. Not limiting roles based on token scopes.")
                                else:
                                    limited_roles = set()
                                    for prop in scope_props:
                                        # Do exact value matches when determining limited role assignments
                                        if prop['pattern'] in jwt_scopes and prop['type'] == 'role':
                                            limited_roles.update(prop['value'])

                                    # The resulting role assignment should be the intersection of the roles derived from the token's scopes and the user's existing roles. This ensures that the user cannot gain additional privileges beyond what they already have via the middle-tier service.
                                    roles = list(set(roles).intersection(limited_roles))

                        if return_user:
                            return user, roles, impersonator
                        return user['uname'], roles, impersonator
            msg = ", ".join([f"{k}={v}" for k, v in profile_identifiers.items() if v is not None])
            raise AuthenticationException(f"User not found - No matching user for the following identifiers ({msg})")


        raise AuthenticationException("Invalid token - No matching signing key found")

    return None, None, None
